<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; Supervised Learning – Data Analytics for Sense-Making</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-vision.html" rel="next">
<link href="./07-simulation.html" rel="prev">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2b3a058f3f598cb5398490cdc55809d4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-K3T2VC9F47"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-K3T2VC9F47', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-supervised.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Supervised Learning</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Data Analytics for Sense-Making</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-unsupervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Natural Language Processing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-supervised.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-vision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Computer Vision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Academic References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#sec-08-top" id="toc-sec-08-top" class="nav-link active" data-scroll-target="#sec-08-top"><span class="header-section-number">8.1</span> Introduction</a></li>
  <li><a href="#classification-versus-regression" id="toc-classification-versus-regression" class="nav-link" data-scroll-target="#classification-versus-regression"><span class="header-section-number">8.2</span> Classification versus Regression</a></li>
  <li><a href="#supervised-learning-workflow" id="toc-supervised-learning-workflow" class="nav-link" data-scroll-target="#supervised-learning-workflow"><span class="header-section-number">8.3</span> Supervised Learning Workflow</a></li>
  <li><a href="#scikit-learn" id="toc-scikit-learn" class="nav-link" data-scroll-target="#scikit-learn"><span class="header-section-number">8.4</span> Scikit-learn</a></li>
  <li><a href="#measures-of-performance" id="toc-measures-of-performance" class="nav-link" data-scroll-target="#measures-of-performance"><span class="header-section-number">8.5</span> Measures of Performance</a></li>
  <li><a href="#classification" id="toc-classification" class="nav-link" data-scroll-target="#classification"><span class="header-section-number">8.6</span> Classification</a></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">8.7</span> Regression</a></li>
  <li><a href="#sec-08-interpretability" id="toc-sec-08-interpretability" class="nav-link" data-scroll-target="#sec-08-interpretability"><span class="header-section-number">8.8</span> Interpretability of Models</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.9</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8.10</span> References</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">8.11</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Supervised Learning</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-08-top" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-08-top"><span class="header-section-number">8.1</span> Introduction</h2>
<p>In supervised learning, our goal is to develop a model that can predict a quantity of interest from a set of features. In this process,</p>
<ul>
<li>Algorithms learn from a training set of labelled examples.</li>
<li>This training set is meant to be representative of the set of all possible inputs.</li>
<li>Example algorithms include logistic regression, support vector machines, decision trees and random forests. Regression models can also be used for supervised learning.</li>
</ul>
<p>Here are some examples:</p>
<ol type="1">
<li>We wish to predict if a student will graduate from university or not, based on his/her ‘A’ level results.</li>
<li>We wish to predict tomorrow’s stock price based on today’s price.</li>
</ol>
</section>
<section id="classification-versus-regression" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="classification-versus-regression"><span class="header-section-number">8.2</span> Classification versus Regression</h2>
<p>If the answer to the question (supervised learning problem) we are facing is either YES or NO, then what we have is a <strong>classification</strong> problem. Here are some examples:</p>
<ul>
<li>Given the results of a clinical test, does this patient suffer from diabetes?</li>
<li>Given an MRI, is there a tumor?</li>
</ul>
<p>On the other hand, if we are trying to predict a real-valued quantity, then we are faced with a <strong>regression</strong> problem.</p>
<ul>
<li>Given the details about an apartment, what will the rental be?</li>
<li>Given historical transactions of a customer, how much is he likely to spend on his next purchase?</li>
</ul>
</section>
<section id="supervised-learning-workflow" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="supervised-learning-workflow"><span class="header-section-number">8.3</span> Supervised Learning Workflow</h2>
<div id="fig-sklearn-workflow" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sklearn-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/grid_search_workflow_sklearn.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sklearn-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: Figure from sklearn documentation
</figcaption>
</figure>
</div>
<p>The overall workflow in supervised learning is as shown in <a href="#fig-sklearn-workflow" class="quarto-xref">Figure&nbsp;<span>8.1</span></a>. Here are the specific details:</p>
<ol type="1">
<li>Split up a dataset into training and test datasets, typically along a 80/20 or 75/25 split. <strong>Do not touch the test data again until the end.</strong></li>
<li>Preprocess/clean the training data and store the parameters for later use on the test data.
<ul>
<li>Example preprocessings are scaling, one-hot encoding, PC decomposition, etc.</li>
</ul></li>
<li>Decide on what models you wish to try. Each model has parameters to be fit (from the data), and <strong>hyperparameters</strong> to be chosen by you.
<ul>
<li>Example models are k-nearest neighbours (KNN) and random forests.
<ul>
<li>A hyperparameter for KNN is the number of neighbours to use.</li>
<li>A hyperparameter for random forests is the number of trees.</li>
</ul></li>
<li>Hyperparameters usually control the <strong>complexity</strong> of a model. If a model is too complex, it will over-fit to the training data but fare poorly on the test data.</li>
</ul></li>
<li>Use <strong>cross-validation</strong> or a set-aside validation set to decide on the hyperparameters for your chosen estimator. To fit the parameters for a particular hyperparameter configuration, we typically minimise a loss function or error metric.</li>
<li>Once you are satisfied with your choice(s) or model, evaluate the selected model on the test set to obtain an estimate of your generalisation error.</li>
</ol>
</section>
<section id="scikit-learn" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="scikit-learn"><span class="header-section-number">8.4</span> Scikit-learn</h2>
<p>Scikit-learn is a library in Python which has several useful functions used in machine learning. The library has many algorithms for classification, regression, clustering and other machine learning methods. It uses other libraries like NumPy and matplotlib which are also used in this course. The website for scikit-learn is an excellent source of examples and tips on using the functions within this package (see the references).</p>
<p>All objects in scikit-learn have common access points. The three main interfaces are:</p>
<ol type="1">
<li>Estimator interface - <code>fit()</code> method.
<ul>
<li>This function allows us to build and fit models.</li>
<li>Any object that can estimate some parameters based on a dataset is an <em>estimator</em>.</li>
<li>Estimation is performed by the <code>fit()</code> method. This method takes in two datasets as arguments (the input data, and the corresponding output/labels).</li>
</ul></li>
<li>Predictor interface - <code>predict()</code> method.
<ul>
<li>This function allows us to make predictions.</li>
<li>Estimators capable of making predictions when given a dataset are called <em>predictors</em>.</li>
<li>A predictor has a <code>predict()</code> method. It takes in a dataset of new instances and returns a dataset of corresponding predictions.</li>
</ul></li>
<li>Transformer interface - <code>transform()</code> method.
<ul>
<li>This function is for converting data.</li>
<li>Estimators which can also transform a dataset are called <em>transformers</em>.</li>
<li>Transformations are carried out by the <code>transform()</code> method.</li>
<li>This method takes in the dataset to transform as a parameter and returns the transformed dataset.</li>
<li>We will not have too much time to spend on the transformer interface in this course.</li>
</ul></li>
</ol>
<section id="input-data-structure" class="level3">
<h3 class="anchored" data-anchor-id="input-data-structure">Input Data Structure</h3>
<p>For supervised learning problems in scikit-learn, the input data has to be structured in NumPy-like arrays.</p>
<p>The <strong>feature matrix X</strong>, of shape <span class="math inline">\(n\)</span> by <span class="math inline">\(d\)</span> contains features: * <span class="math inline">\(n\)</span> rows: the number of samples * <span class="math inline">\(d\)</span> columns: the number of features or distinct traits used to describe each item in a quantitative manner</p>
<p>Each row in the feature matrix is referred to as a sample, example or an instance.</p>
<p><span class="math display">\[
\text{feature matrix:} \quad \mathbf{X}_{n\times d} =
\begin{bmatrix}
x_{1,1} &amp; x_{1,2} &amp; \ldots &amp; x_{1,d}\\
\cdots &amp; \cdots &amp; \cdots &amp; \cdots \\
x_{n,1} &amp; x_{n,2} &amp; \ldots &amp; x_{n,d}
\end{bmatrix}
\]</span></p>
<p>A <strong>label vector y</strong> stores the target values. This vector stores the true output value for each corresponding sample (row) in matrix X.</p>
<p><span class="math display">\[
\text{label vector:} \quad \mathbf{y} =
\begin{bmatrix}
y_1 &amp; y_2 &amp; \ldots &amp; y_n
\end{bmatrix}^T
\]</span></p>
<div id="8a39d907" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a><span class="im">from</span> itables <span class="im">import</span> show</span>
<span id="cb1-6"><a href="#cb1-6"></a></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="im">from</span> lime <span class="im">import</span> lime_tabular</span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="im">from</span> sklearn <span class="im">import</span> tree</span>
<span id="cb1-10"><a href="#cb1-10"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier, RandomForestRegressor</span>
<span id="cb1-11"><a href="#cb1-11"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> (</span>
<span id="cb1-12"><a href="#cb1-12"></a>  accuracy_score, f1_score, confusion_matrix, </span>
<span id="cb1-13"><a href="#cb1-13"></a>  ConfusionMatrixDisplay, precision_score, recall_score, r2_score</span>
<span id="cb1-14"><a href="#cb1-14"></a>  )</span>
<span id="cb1-15"><a href="#cb1-15"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> (</span>
<span id="cb1-16"><a href="#cb1-16"></a>    cross_val_score, cross_validate, ShuffleSplit, </span>
<span id="cb1-17"><a href="#cb1-17"></a>    learning_curve, validation_curve, GridSearchCV, train_test_split</span>
<span id="cb1-18"><a href="#cb1-18"></a>    )</span>
<span id="cb1-19"><a href="#cb1-19"></a><span class="im">from</span> sklearn.inspection <span class="im">import</span> permutation_importance</span>
<span id="cb1-20"><a href="#cb1-20"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> KNeighborsRegressor</span>
<span id="cb1-21"><a href="#cb1-21"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-22"><a href="#cb1-22"></a><span class="im">from</span> sklearn.inspection <span class="im">import</span> PartialDependenceDisplay, partial_dependence</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="measures-of-performance" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="measures-of-performance"><span class="header-section-number">8.5</span> Measures of Performance</h2>
<section id="for-classification" class="level3">
<h3 class="anchored" data-anchor-id="for-classification">For Classification</h3>
<p>Before we head into creating classifiers which will help us predict heart failure, let’s understand what determines the usefulness of a classifier. For now, we focus on the case where the outcome is binary (only two possible values for <span class="math inline">\(y_i\)</span>).</p>
<section id="accuracy" class="level4">
<h4 class="anchored" data-anchor-id="accuracy">Accuracy</h4>
<p>A basic measure of performance would be the <em>accuracy</em> of predictions.</p>
<p><span class="math display">\[
\text{accuracy} = \frac{\text{Number of correct predictions}}{\text{Total number of predictions}}
\]</span></p>
<p>When more detailed analysis is needed, partial performance metrics can be presented in a <em>confusion matrix</em>. A confusion matrix is a contingency table that arises from cross-classification of predictions and the actual outcomes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Positive prediction</strong></td>
<td><strong>Negative prediction</strong></td>
</tr>
<tr class="even">
<td><strong>Positive truth</strong></td>
<td>TP</td>
<td>FN</td>
</tr>
<tr class="odd">
<td><strong>Negative truth</strong></td>
<td>FP</td>
<td>TN</td>
</tr>
</tbody>
</table>
<p>In the confusion matrix, there are 4 possible cases:</p>
<ul>
<li>True positives (TP)
<ul>
<li>Classifier predicts sample as positive and it really is so.</li>
</ul></li>
<li>False positives (FP)
<ul>
<li>Classifier predicts sample as positive but in truth, it is negative. <strong>Incorrect prediction</strong></li>
</ul></li>
<li>True negatives (TN)
<ul>
<li>Classifier predicts sample as negative and it really is so.</li>
</ul></li>
<li>False negatives (FN)
<ul>
<li>Classifier predicts sample as negative but in truth, it is positive. <strong>Incorrect prediction</strong></li>
</ul></li>
</ul>
</section>
<section id="precision-and-recall" class="level4">
<h4 class="anchored" data-anchor-id="precision-and-recall">Precision and Recall</h4>
<p>With the confusion matrix, more performance metrics can be defined besides the accuracy of a classifier.</p>
<p>The <strong>recall</strong> of a classifier is the proportion of TP correctly identified:</p>
<p><span class="math display">\[
\text{recall}=  \frac{\text{TP}}{\text{TP + FN}}
\]</span></p>
<p>The <strong>precision</strong> of a classifier is the proportion of predicted positives that are truly positive:</p>
<p><span class="math display">\[
\text{precision} =  \frac{\text{TP}}{\text{TP + FP}}
\]</span></p>
<p>Depending on the context of the problem, it may be more important to have better recall than precision. In the above, we have defined recall and precision for the <em>positive</em> category outcome. There are analogous definitions for the <em>negative</em> outcome.</p>
<p>Note that recall is also sometimes referred to as the True Positive Rate (TPR), while <span class="math inline">\((1 - \text{precision})\)</span> is also referred to as the False Positive Rate (FPR).</p>
</section>
<section id="f1-score" class="level4">
<h4 class="anchored" data-anchor-id="f1-score">F1 score</h4>
<p>The harmonic mean of two numbers <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> is <span class="math display">\[
\left( \frac{1/x_1 + 1/x_2}{2} \right)^{-1}
\]</span></p>
<p>We can combine precision and recall into one score using their harmonic mean: <span class="math display">\[
F1 = 2 \times \frac{\text{precision} \times \text{recall}}{\text{precision} +
\text{recall}}
\]</span></p>
<p>Roughly, the F1 score is a summary of how good the classifier is in terms of both precision and recall. The F1 score is preferable to the simple arithmetic mean of precision and recall, because it ensures that both are high; the F1 score will be significantly lower than the mean if one of precision or recall is very low.</p>
</section>
</section>
<section id="for-regression" class="level3">
<h3 class="anchored" data-anchor-id="for-regression">For Regression</h3>
<section id="root-mean-squared-error" class="level4">
<h4 class="anchored" data-anchor-id="root-mean-squared-error">Root Mean Squared Error</h4>
<p>For regression problems, the typical measure of accuracy is RMSE. Let * <span class="math inline">\(y_i\)</span> be the observed quantity (that we wish to predict), for <span class="math inline">\(i=1,\ldots, n\)</span>, and * <span class="math inline">\(\hat{y}_i\)</span> be the predicted quantity for observation <span class="math inline">\(i\)</span>.</p>
<p>The RMSE is defined to be:</p>
<p><span class="math display">\[
RMSE = \sqrt{\frac{1}{n} \sum_{i=1}^n (y_i - \hat{y}_i)^2}
\]</span></p>
</section>
<section id="mean-absolute-error" class="level4">
<h4 class="anchored" data-anchor-id="mean-absolute-error">Mean Absolute Error</h4>
<p>Using the RMSE amplifies the effect of outliers because of the square-term in the equation. Hence, in order to be resistant to outliers, one alternative is to the mean absolute error.</p>
<p><span class="math display">\[
MAE = \frac{1}{n} \sum_{i=1}^n |y_i - \hat{y}_i|
\]</span></p>
</section>
</section>
</section>
<section id="classification" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="classification"><span class="header-section-number">8.6</span> Classification</h2>
<p>In this section, we demonstrate how we can use <code>scikit-learn</code> to perform supervised learning on a classification problem.</p>
<div id="exm-heart-failure-1" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.1 (Heart failure)</strong></span> </p>
<p>This dataset, from the <a href="https://archive.ics.uci.edu/dataset/519/heart+failure+clinical+records">UCI machine learning repository</a> contains records on 299 patients who had heart failure. The data was collected during the follow-up period; each patient had 13 clinical features recorded. The primary variable of interest (<span class="math inline">\(y\)</span>) was whether they died or not. Here are more details about each column:</p>
<ul>
<li><code>age</code>: age of the patient (years)</li>
<li><code>anaemia</code>: decrease of red blood cells or hemoglobin (boolean)</li>
<li><code>creatinine phosphokinase</code> (CPK): level of the CPK enzyme in the blood (mcg/L)</li>
<li><code>diabetes</code>: if the patient has diabetes (boolean)</li>
<li><code>ejection_fraction</code>: percentage of blood leaving the heart at each contraction (percentage)</li>
<li><code>high_blood_pressure</code>: if the patient has hypertension (boolean)</li>
<li><code>platelets</code>: platelets in the blood (kiloplatelets/mL)</li>
<li><code>sex</code>: woman or man (binary)</li>
<li><code>serum_creatinine</code>: level of serum creatinine in the blood (mg/dL)</li>
<li><code>serum_sodium</code>: level of serum sodium in the blood (mEq/L)</li>
<li><code>smoking</code>: if the patient smokes or not (boolean)</li>
<li><code>time</code>: follow-up period (days)</li>
<li><code>DEATH_EVENT</code>: if the patient died during the follow-up period (boolean). This is the categorical outcome that we wish to predict.</li>
</ul>
<div id="de825304" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a>hf <span class="op">=</span> pd.read_csv(<span class="st">"data/heart+failure+clinical+records/"</span><span class="op">+</span></span>
<span id="cb2-2"><a href="#cb2-2"></a>                 <span class="st">"heart_failure_clinical_records_dataset.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="bu">print</span>(hf.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1  </code></pre>
</div>
</div>
</div>
<section id="sec-08-dec-tree" class="level3">
<h3 class="anchored" data-anchor-id="sec-08-dec-tree">Decision Tree</h3>
<p>To begin our journey into supervised learning, we shall fit a decision tree to this dataset. A decision tree consists of a hierarchal set of rules, that when followed, will return a prediction for an individual observation. Each is a (typically binary) split of one of the features in the observation. One of the main advantages of decision tree classifiers is that they are easy to interpret. However, some disadvantages are that: They tend to overfit to a dataset, and they have high variability. This latter point means that a small change in the training data <em>could</em> lead to vastly different predictions. Although in this example we focus on classification, a decision tree can also be used for regression.</p>
<p>In this first example, we shall only split the data into a test and training set. We shall fit the tree using the training set, and then apply the model to the test set.</p>
<div id="17b140a9" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a>y <span class="op">=</span> hf.DEATH_EVENT</span>
<span id="cb4-2"><a href="#cb4-2"></a>X <span class="op">=</span> hf.iloc[:, <span class="dv">0</span>:<span class="dv">12</span>]</span>
<span id="cb4-3"><a href="#cb4-3"></a></span>
<span id="cb4-4"><a href="#cb4-4"></a>clf <span class="op">=</span> tree.DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>max_depth</code> of a decision is the maximum number of splits down each branch of a tree. If it is not specified, it is possible that the splits continue until the terminal nodes are homogeneous. This could result in overfitting of the tree to this particular dataset.</p>
<div id="162d9ff0" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a>X_train,X_test,y_train,y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.25</span>, </span>
<span id="cb5-2"><a href="#cb5-2"></a>                                                 random_state<span class="op">=</span><span class="dv">41</span>, stratify<span class="op">=</span>y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <code>train_test_split</code> divides the data into a training and test set. When doing so, the function will attempt to ensure that the proportion of classes in both the training and test sets are roughly equal to the proportion in the overall dataset.</p>
<div id="d64e6a67" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a><span class="bu">print</span>(<span class="ss">f"The proportion of 1's in the overall data is </span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">."</span>)</span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="bu">print</span>(<span class="ss">f"The proportion of 1's in the training data is </span><span class="sc">{</span>y_train<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">."</span>)</span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="bu">print</span>(<span class="ss">f"The proportion of 1's in the test data is </span><span class="sc">{</span>y_test<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The proportion of 1's in the overall data is 0.321.
The proportion of 1's in the training data is 0.321.
The proportion of 1's in the test data is 0.320.</code></pre>
</div>
</div>
<div id="exm-heart-failure-2" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.2 (Heart failure decision tree)</strong></span> </p>
<p>All estimators in <code>sklearn</code> have a <code>.fit()</code> method. This routine will use the data to estimate the optimal parameters for the particular model, which in this case is a decision tree.</p>
<div id="7048044d" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1"></a>clf.fit(X_train, y_train,)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Notice that when we call the <code>.fit()</code> method, there is no output object returned; it is just that the parameters in the <code>clf</code> object are updated. We can now use the trained model to make predictions. In this case, we attempt to predict <code>DEATH_EVENT</code> for a randomly selected row in the training data.</p>
<div id="b9ff310b" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1"></a>clf.predict_proba(X_train.sample(random_state<span class="op">=</span><span class="dv">3005</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([[0.66666667, 0.33333333]])</code></pre>
</div>
</div>
</div>
<p>We can visualise the fitted decision tree as follows. This is an important step in understanding and interpreting the fitted model.</p>
<div id="cell-fig-heart-dt" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a>plt.figure(figsize <span class="op">=</span>(<span class="dv">18</span>, <span class="dv">6</span>))</span>
<span id="cb11-2"><a href="#cb11-2"></a>tree.plot_tree(clf,feature_names<span class="op">=</span>X.columns, filled<span class="op">=</span><span class="va">True</span>, max_depth<span class="op">=</span><span class="dv">2</span>)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-heart-dt" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="ht">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heart-dt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-heart-dt-output-1.png" class="quarto-figure quarto-figure-center figure-img" data-fig-pos="ht" width="1358" height="463">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heart-dt-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: Heart failure decision tree
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-heart-dt" class="quarto-xref">Figure&nbsp;<span>8.2</span></a> visualises the rules in the first two layers (depth 2) of the tree. First off, notice that the tree is upside down, with the root on top; the terminal nodes (or boxes) at the bottom are referred to as the leaves. To understand the tree, consider using it to obtain a new prediction, with the following two features:</p>
<ul>
<li><code>time</code>=70, <code>ejection_fraction</code> = 40.5</li>
</ul>
<p>Since the value for the <code>time</code> variable is less than or equal to 73.5, we go down the left branch. Next, since <code>time</code> is more than 52.0, we go down the right branch. Finally, since <code>ejection_fraction</code> is more than 30, we would go down the right branch, and so on.</p>
<p>The information in the node summarises the splitting rule at that node. <code>samples</code> refers to the number of observations from the training set that would reach that node. The <code>value</code> vector indicates the count of each output class that has reached that node. For instance, for the blue node at the second level on the extreme left, out of the 44 observations that reached it, 4 were class 0 and 40 were class 1. The Gini impurity index is what is used to decide the split (not the same Gini as the Gini coefficient for income inequality!). For our binary classification problem, the formula for Gini impurity at each node reduces to:</p>
<p><span class="math display">\[
p_0(1 - p_0)
\]</span></p>
<p>where <span class="math inline">\(p_0\)</span> is the proportion of class 0 at that node. If a node consists all 0’s or all 1’s, then the impurity index would be 0. The fitting algorithm tries all features, and all split points for each feature, to obtain the feature and split point that yields the largest drop in impurity at that node.</p>
<p>Before proceeding with the calculation of error metrics, notice the non-linearity of the splits. Both the initial split and the subsequent split on the left are on <code>time</code>. This indicates a non-linear relationship with time, and is not a property of classical models such as out-of-the-box linear regression.</p>
<div id="exm-heart-failure-3" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.3 (Heart failure classification scores)</strong></span> </p>
<p>Performance of classification algorithms are usually presented in the form of a <em>confusion matrix</em>. First we display the results for the training set in <a href="#fig-confusion-training" class="quarto-xref">Figure&nbsp;<span>8.3</span></a>.</p>
<div id="cell-fig-confusion-training" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1"></a>y_pred_train <span class="op">=</span> clf.predict(X_train)</span>
<span id="cb12-2"><a href="#cb12-2"></a>ConfusionMatrixDisplay.from_predictions(y_train, y_pred_train, </span>
<span id="cb12-3"><a href="#cb12-3"></a>                                        text_kw<span class="op">=</span>{<span class="st">'size'</span>: <span class="st">'xx-large'</span>},</span>
<span id="cb12-4"><a href="#cb12-4"></a>                                        labels<span class="op">=</span>clf.classes_, cmap<span class="op">=</span><span class="st">'bone'</span>)<span class="op">;</span></span>
<span id="cb12-5"><a href="#cb12-5"></a><span class="bu">print</span>(<span class="ss">f"""</span></span>
<span id="cb12-6"><a href="#cb12-6"></a><span class="ss">##: For training set:</span></span>
<span id="cb12-7"><a href="#cb12-7"></a><span class="ss">----</span></span>
<span id="cb12-8"><a href="#cb12-8"></a><span class="ss">The precision (for cat. 1) is </span><span class="sc">{</span>precision_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb12-9"><a href="#cb12-9"></a><span class="ss">The recall (for cat. 1) is </span><span class="sc">{</span>recall_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb12-10"><a href="#cb12-10"></a><span class="ss">The accuracy (for cat. 1) is </span><span class="sc">{</span>accuracy_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb12-11"><a href="#cb12-11"></a><span class="ss">The f1-score (for cat. 1) is </span><span class="sc">{</span>f1_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb12-12"><a href="#cb12-12"></a><span class="ss">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
##: For training set:
----
The precision (for cat. 1) is 0.938
The recall (for cat. 1) is 0.833
The accuracy (for cat. 1) is 0.929
The f1-score (for cat. 1) is 0.882
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-confusion-training" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="ht">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-training-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-confusion-training-output-2.png" class="quarto-figure quarto-figure-center figure-img" data-fig-pos="ht" width="504" height="429">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-training-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: Confusion matrix, training set
</figcaption>
</figure>
</div>
</div>
</div>
<p>Next, we display the results for the test set in <a href="#fig-confusion-test" class="quarto-xref">Figure&nbsp;<span>8.4</span></a>.</p>
<div id="cell-fig-confusion-test" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a>y_pred_test <span class="op">=</span> clf.predict(X_test)</span>
<span id="cb14-2"><a href="#cb14-2"></a>ConfusionMatrixDisplay.from_predictions(y_test, y_pred_test,  </span>
<span id="cb14-3"><a href="#cb14-3"></a>                                        text_kw<span class="op">=</span>{<span class="st">'size'</span>: <span class="st">'xx-large'</span>},</span>
<span id="cb14-4"><a href="#cb14-4"></a>                                        labels<span class="op">=</span>clf.classes_, cmap<span class="op">=</span><span class="st">'bone'</span>)<span class="op">;</span></span>
<span id="cb14-5"><a href="#cb14-5"></a><span class="bu">print</span>(<span class="ss">f"""</span></span>
<span id="cb14-6"><a href="#cb14-6"></a><span class="ss">##: For test set:</span></span>
<span id="cb14-7"><a href="#cb14-7"></a><span class="ss">----</span></span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="ss">The accuracy (for cat. 1) is </span><span class="sc">{</span>accuracy_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb14-9"><a href="#cb14-9"></a><span class="ss">The precision (for cat. 1) is </span><span class="sc">{</span>precision_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb14-10"><a href="#cb14-10"></a><span class="ss">The recall (for cat. 1) is </span><span class="sc">{</span>recall_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb14-11"><a href="#cb14-11"></a><span class="ss">The f1-score (for cat. 1) is </span><span class="sc">{</span>f1_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb14-12"><a href="#cb14-12"></a><span class="ss">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
##: For test set:
----
The accuracy (for cat. 1) is 0.760
The precision (for cat. 1) is 0.636
The recall (for cat. 1) is 0.583
The f1-score (for cat. 1) is 0.609
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-confusion-test" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="ht">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-confusion-test-output-2.png" class="quarto-figure quarto-figure-center figure-img" data-fig-pos="ht" width="496" height="429">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Confusion matrix, test set
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>It is normal to observe poorer performance on the test set than on the training set. However, such a large difference in the scores usually indicates that there has been overfitting by the model; it is too tuned to the data in the training set. In supervised learning, we aim for a classifier that performs almost as well on the test data as it does on the training data. That would indicate that the model, with this particular hyperparameter configuration, will perform well on new data that has yet to be seen.</p>
<p>In this particular dataset, we may want to go back to the fitting step, and reduce the <code>max_depth</code>, or to impose a larger number of samples in the leaf nodes via <code>min_samples_leaf</code>.</p>
</section>
<section id="variable-importance" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance">Variable importance</h3>
<p>As we shall discuss in <a href="#sec-08-interpretability" class="quarto-xref"><span>Section 8.8</span></a>, it is important to be able to identify which features are important to the model. This allows non-technical folk in your team (who could be end-user domain experts, or upper management) to have faith in your models. If the features that are identified to be important align with what the domain experts know or intuit, that provides more buy-in for your analyses and recommendations.</p>
<p>We shall demonstrate two types of feature importance:</p>
<ol type="1">
<li><em>Permutation based feature importance</em>. It works by permuting one of the features at a time, and measuring the drop in accuracy on the test set. The intuition is that, if a variable is highly important, randomising it will cause a sharp drop in predictive value.</li>
<li><em>Partial dependence plots (PDP)</em>. A PDP can be generated for each feature in the model, or a pair of features. Each PDP is generated by:
<ol type="1">
<li>Vary the feature over a range of values</li>
<li>For each feature value in that range, average the predictions over all values of <em>other</em> variables occuring in the training data.</li>
</ol></li>
</ol>
<p>There are certain caveats with using the above measures. One is that these measures are indicative of how important a feature is to a particular model, not to predictive value. Hence an unimportant feature for a poor model (in terms of accuracy) could in fact be an important feature for a good model! Second, in the permutation approach, the importance of a variable may not show up if certain features are highly correlated (dropping one of them may have no effect because the other feature is still present in the model).</p>
<div id="exm-heart-failure-4" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.4 (Heart failure permutation based)</strong></span> </p>
<p>Here is how we can use <code>sklearn</code> to obtain the importance of variables based on permutating the values to break the relationship.</p>
<div id="cell-fig-var-impt-perm" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a>result <span class="op">=</span> permutation_importance(clf, X_test, y_test,  </span>
<span id="cb16-2"><a href="#cb16-2"></a>                                n_repeats<span class="op">=</span><span class="dv">30</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb16-3"><a href="#cb16-3"></a></span>
<span id="cb16-4"><a href="#cb16-4"></a>sorted_importances_idx <span class="op">=</span> result.importances_mean.argsort()</span>
<span id="cb16-5"><a href="#cb16-5"></a>importances <span class="op">=</span> pd.DataFrame(</span>
<span id="cb16-6"><a href="#cb16-6"></a>    result.importances[sorted_importances_idx].T,</span>
<span id="cb16-7"><a href="#cb16-7"></a>    columns<span class="op">=</span>X.columns[sorted_importances_idx],</span>
<span id="cb16-8"><a href="#cb16-8"></a>)</span>
<span id="cb16-9"><a href="#cb16-9"></a>ax <span class="op">=</span> importances.plot.box(vert<span class="op">=</span><span class="va">False</span>, whis<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb16-10"><a href="#cb16-10"></a>ax.set_title(<span class="st">"Permutation Importances (test set)"</span>)</span>
<span id="cb16-11"><a href="#cb16-11"></a>ax.axvline(x<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"k"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb16-12"><a href="#cb16-12"></a>ax.set_xlabel(<span class="st">"Decrease in accuracy score"</span>)</span>
<span id="cb16-13"><a href="#cb16-13"></a>ax.figure.tight_layout()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-var-impt-perm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="ht">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-var-impt-perm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-var-impt-perm-output-1.png" class="quarto-figure quarto-figure-center figure-img" data-fig-pos="ht" width="661" height="470">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-var-impt-perm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.5: Variable importance, permutation approach
</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-var-impt-perm" class="quarto-xref">Figure&nbsp;<span>8.5</span></a>, we can see that <code>time</code> and <code>ejection_fraction</code> are the top 2 in terms of importance when assessing generalisability to test set.</p>
</div>
<p><br></p>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section"></h4>
<div id="exm-heart-failure-5" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.5 (Heart failure partial dependence)</strong></span> </p>
<p>In order to obtain PDP plots, the features need to be float-point, not integer. The following code snippets converts <code>creatinine_phosphokinase</code> and <code>serum_sodium</code> into floats.</p>
<div id="c86400fd" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1"></a>X_train2 <span class="op">=</span> X_train.copy()</span>
<span id="cb17-2"><a href="#cb17-2"></a></span>
<span id="cb17-3"><a href="#cb17-3"></a>X_train2[<span class="st">'creatinine_phosphokinase'</span>] <span class="op">=</span> X_train2[<span class="st">'creatinine_phosphokinase'</span>].astype(<span class="bu">float</span>)</span>
<span id="cb17-4"><a href="#cb17-4"></a>X_train2[<span class="st">'serum_sodium'</span>] <span class="op">=</span> X_train2[<span class="st">'serum_sodium'</span>].astype(<span class="bu">float</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now we can create and display the PDP plots for 5 individual features, and one double-feature.</p>
<div id="cell-fig-var-impt-pdp" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1"></a>_, ax <span class="op">=</span> plt.subplots(ncols<span class="op">=</span><span class="dv">3</span>, nrows<span class="op">=</span><span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-2"><a href="#cb18-2"></a>features_info <span class="op">=</span> {</span>
<span id="cb18-3"><a href="#cb18-3"></a>    <span class="st">"features"</span>: [<span class="st">"age"</span>, <span class="st">"creatinine_phosphokinase"</span>, <span class="st">"platelets"</span>, </span>
<span id="cb18-4"><a href="#cb18-4"></a>                 <span class="st">"serum_creatinine"</span>, <span class="st">"serum_sodium"</span>, (<span class="st">"age"</span>, <span class="st">"serum_creatinine"</span>),</span>
<span id="cb18-5"><a href="#cb18-5"></a>                ],</span>
<span id="cb18-6"><a href="#cb18-6"></a>    <span class="st">"kind"</span>: <span class="st">"average"</span>,</span>
<span id="cb18-7"><a href="#cb18-7"></a>}</span>
<span id="cb18-8"><a href="#cb18-8"></a>display <span class="op">=</span> PartialDependenceDisplay.from_estimator(</span>
<span id="cb18-9"><a href="#cb18-9"></a>    clf,</span>
<span id="cb18-10"><a href="#cb18-10"></a>    X_train2,</span>
<span id="cb18-11"><a href="#cb18-11"></a>    <span class="op">**</span>features_info,</span>
<span id="cb18-12"><a href="#cb18-12"></a>    ax<span class="op">=</span>ax,</span>
<span id="cb18-13"><a href="#cb18-13"></a>    contour_kw <span class="op">=</span> {<span class="st">'cmap'</span>: <span class="st">"Reds"</span>}</span>
<span id="cb18-14"><a href="#cb18-14"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-var-impt-pdp" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" data-fig-pos="ht">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-var-impt-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-var-impt-pdp-output-1.png" class="quarto-figure quarto-figure-center figure-img" data-fig-pos="ht" width="1163" height="587">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-var-impt-pdp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.6: Variable importance, partial dependence
</figcaption>
</figure>
</div>
</div>
</div>
<p>PDP are meant to visualise the relationship that has been learned in the training set; hence it is not usually created with the test set. From <a href="#fig-var-impt-pdp" class="quarto-xref">Figure&nbsp;<span>8.6</span></a>, we can interpret that when other variables are already in the model, age returns a visible bump in the probability of death at around age 80. <code>serum_creatinine</code> is associated with a similar increase, but at low levels. The final plot, at the lower right, darker reds indicate higher probability of death.</p>
</div>
</section>
</section>
<section id="sec-08-forest" class="level3">
<h3 class="anchored" data-anchor-id="sec-08-forest">Random Forest</h3>
<p>A random forest model is an example of an ensemble model. It aims to fix the weakness of decision trees by introducing a little noise in the fitting process. A random forest is in fact a collection of decision trees, with some added modifications. First of all, each tree in a random forest is fit using a bootstrapped version of the training data. Second, at each split, not all features are considered - only a sample of all available features is considered. When a classification prediction is eventually made, it is made by averaging the predictions from all the individual trees. Through the introduction of these perturbations, the eventual model has lower variance (less susceptible to changes in the data), thus generalising to new data better.</p>
<p>Clearly an important property of the random forest is the number of trees to be fitted. This is known as a hyperparameter. More trees leads to a more complex model, which could overfit to the data. scikit-learn provides convenient grid search utilities for identifying the optimal number of trees through. This process, known as hyperparameter tuning, uses cross-validation on the training dataset.</p>
<p>Cross-validation begins with a split of the training data into <span class="math inline">\(k\)</span> blocks (typically <span class="math inline">\(k=5\)</span>). Then, for each block <span class="math inline">\(i\)</span>,</p>
<ol type="1">
<li>Set aside block <span class="math inline">\(i\)</span>, and use the <em>remaining</em> data to fit the model.</li>
<li>Use the fitted model to predict on block <span class="math inline">\(i\)</span>, thus obtaining one estimate of generalised error.</li>
</ol>
<p>The process yields <span class="math inline">\(k\)</span> estimates of error - one for each block that was set aside. This can be used to compare between hyperparamter settings.</p>
<div id="exm-heart-failure-6" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.6 (Heart failure grid search)</strong></span> </p>
<p>Earlier, in <a href="#exm-heart-failure-3" class="quarto-xref">Example&nbsp;<span>8.3</span></a>, we noticed that our decision tree had been overfitting to the data. In this example, we try to identify the optimal <code>max_depth</code> parameter for the trees by testing models with different depths, ranging from 1 to 10, and identifying the one with the best generalised error.</p>
<div id="ec14f008" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1"></a>p_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>, <span class="dv">1</span>)</span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="co">#list(p_range)</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>cv_search <span class="op">=</span> GridSearchCV(RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">20</span>, random_state<span class="op">=</span><span class="dv">21</span>), </span>
<span id="cb19-4"><a href="#cb19-4"></a>                         return_train_score<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb19-5"><a href="#cb19-5"></a>                         param_grid <span class="op">=</span>{<span class="st">'max_depth'</span>: p_range},</span>
<span id="cb19-6"><a href="#cb19-6"></a>                         scoring <span class="op">=</span> <span class="st">'accuracy'</span>, cv<span class="op">=</span> <span class="dv">5</span>, verbose<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb19-7"><a href="#cb19-7"></a>cv_search.fit(X_train, y_train)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 5 folds for each of 10 candidates, totalling 50 fits</code></pre>
</div>
</div>
<p>After calling the <code>.fit()</code> method, the optimal parameters are available for persual:</p>
<div id="299a73e0" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1"></a>cv_search.best_estimator_<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
<p>It is also possible, at this point, to extract the training and test scores for each cross-validation set, and to then plot the validation curve.</p>
<div id="cell-fig-valid-curve" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1"></a>train_means <span class="op">=</span> cv_search.cv_results_[<span class="st">'mean_train_score'</span>]</span>
<span id="cb22-2"><a href="#cb22-2"></a>train_sd <span class="op">=</span> cv_search.cv_results_[<span class="st">'std_train_score'</span>]</span>
<span id="cb22-3"><a href="#cb22-3"></a></span>
<span id="cb22-4"><a href="#cb22-4"></a>test_means <span class="op">=</span> cv_search.cv_results_[<span class="st">'mean_test_score'</span>]</span>
<span id="cb22-5"><a href="#cb22-5"></a>test_sd <span class="op">=</span> cv_search.cv_results_[<span class="st">'std_test_score'</span>]</span>
<span id="cb22-6"><a href="#cb22-6"></a>plt.plot(p_range, train_means, <span class="st">'o-'</span>, label<span class="op">=</span><span class="st">'Training'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb22-7"><a href="#cb22-7"></a>plt.fill_between(p_range, train_means<span class="op">-</span>train_sd, train_means<span class="op">+</span>train_sd, </span>
<span id="cb22-8"><a href="#cb22-8"></a>                 color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb22-9"><a href="#cb22-9"></a></span>
<span id="cb22-10"><a href="#cb22-10"></a>plt.plot(p_range, test_means, <span class="st">'o-'</span>, label<span class="op">=</span><span class="st">'CV (Test)'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb22-11"><a href="#cb22-11"></a>plt.fill_between(p_range, test_means<span class="op">-</span>test_sd, test_means<span class="op">+</span>test_sd, </span>
<span id="cb22-12"><a href="#cb22-12"></a>                 color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb22-13"><a href="#cb22-13"></a></span>
<span id="cb22-14"><a href="#cb22-14"></a>plt.legend(loc<span class="op">=</span><span class="st">'lower right'</span>)<span class="op">;</span>plt.ylabel(<span class="st">'Accuracy'</span>)<span class="op">;</span></span>
<span id="cb22-15"><a href="#cb22-15"></a>plt.xlabel(<span class="st">'Complexity'</span>)<span class="op">;</span>plt.title(<span class="st">'Validation Curve'</span>)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-valid-curve" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-valid-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-valid-curve-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="597" height="449">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-valid-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.7: Validation curve, random forest
</figcaption>
</figure>
</div>
</div>
</div>
<p>From <a href="#fig-valid-curve" class="quarto-xref">Figure&nbsp;<span>8.7</span></a>, we can see that as the max. depth increases, both the training and test errors increase sharply, and then plateau. It even appears that the test error appears to come down. As we discussed, it is normal for the test error to be lower than the training set. Observe that with too high a complexity, accuracy in the training set approaches 1. From the curve, a good choice for the <code>max_depth</code> parameter is 3, because:</p>
<ul>
<li>The test error for this value is close to the training error.</li>
<li>Any <code>max_depth</code> larger than this would lead to overfitting (fitting the noise patterns in the data to the model).</li>
<li>The convention is to take the smallest complexity that is not more than 1 standard error away from the best performing model.</li>
</ul>
<div id="exm-heart-failure-7" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.7 (Heart failure random forest classification scores)</strong></span> </p>
<p>In this example, we use the optimal <code>max_depth</code> to fit a random forest, and assess the test error.</p>
<div id="c332873c" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1"></a>rf <span class="op">=</span> RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">20</span>, max_depth<span class="op">=</span><span class="dv">3</span>, random_state<span class="op">=</span><span class="dv">40</span>)</span>
<span id="cb23-2"><a href="#cb23-2"></a>rf.fit(X_train, y_train)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The following code returns the error from the training error.</p>
<div id="9d9fedf9" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1"></a>y_pred_train <span class="op">=</span> rf.predict(X_train)</span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="bu">print</span>(<span class="ss">f"""</span></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="ss">For training set:</span></span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="ss">-----------------</span></span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="ss">The precision (for cat. 1) is </span><span class="sc">{</span>precision_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="ss">The recall (for cat. 1) is </span><span class="sc">{</span>recall_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb24-7"><a href="#cb24-7"></a><span class="ss">The accuracy (for cat. 1) is </span><span class="sc">{</span>accuracy_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb24-8"><a href="#cb24-8"></a><span class="ss">The f1-score (for cat. 1) is </span><span class="sc">{</span>f1_score(y_train, y_pred_train)<span class="sc">:.3f}</span></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="ss">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
For training set:
-----------------
The precision (for cat. 1) is 0.950
The recall (for cat. 1) is 0.792
The accuracy (for cat. 1) is 0.920
The f1-score (for cat. 1) is 0.864
</code></pre>
</div>
</div>
<p>Here is the test error.</p>
<div id="a4a4b1c3" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1"></a>y_pred_test <span class="op">=</span> rf.predict(X_test)</span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="bu">print</span>(<span class="ss">f"""</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="ss">For test set:</span></span>
<span id="cb26-4"><a href="#cb26-4"></a><span class="ss">-------------</span></span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="ss">The precision (for cat. 1) is </span><span class="sc">{</span>precision_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="ss">The recall (for cat. 1) is </span><span class="sc">{</span>recall_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb26-7"><a href="#cb26-7"></a><span class="ss">The accuracy (for cat. 1) is </span><span class="sc">{</span>accuracy_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb26-8"><a href="#cb26-8"></a><span class="ss">The f1-score (for cat. 1) is </span><span class="sc">{</span>f1_score(y_test, y_pred_test)<span class="sc">:.3f}</span></span>
<span id="cb26-9"><a href="#cb26-9"></a><span class="ss">"""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
For test set:
-------------
The precision (for cat. 1) is 0.762
The recall (for cat. 1) is 0.667
The accuracy (for cat. 1) is 0.827
The f1-score (for cat. 1) is 0.711
</code></pre>
</div>
</div>
<p>Compared with the earlier single decision tree, we have obtained an improved test accuracy (from 0.760 to 0.827).</p>
</div>
</section>
</section>
<section id="regression" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="regression"><span class="header-section-number">8.7</span> Regression</h2>
<p>Just to demonstrate the use of random forests for regression, we return to the Taiwan dataset. In our scoring, instead of using RMSE or MAE, we shall use the <span class="math inline">\(R^2\)</span>. First, we read the Taiwan data into Python and transform each column to have mean 0 and sd 1.</p>
<div id="81d4ca94" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1"></a>re2 <span class="op">=</span> pd.read_csv(<span class="st">"data/taiwan_dataset.csv"</span>)</span>
<span id="cb28-2"><a href="#cb28-2"></a></span>
<span id="cb28-3"><a href="#cb28-3"></a>X_re <span class="op">=</span> re2.loc[:, [<span class="st">'trans_date'</span>, <span class="st">'house_age'</span>, <span class="st">'dist_MRT'</span>, </span>
<span id="cb28-4"><a href="#cb28-4"></a>                   <span class="st">'num_stores'</span>, <span class="st">'Xs'</span>, <span class="st">'Ys'</span>]]</span>
<span id="cb28-5"><a href="#cb28-5"></a>re_scaler <span class="op">=</span> StandardScaler().fit(X_re)</span>
<span id="cb28-6"><a href="#cb28-6"></a>X_re_scaled <span class="op">=</span> re_scaler.transform(X_re)</span>
<span id="cb28-7"><a href="#cb28-7"></a>y_re <span class="op">=</span> re2.price</span>
<span id="cb28-8"><a href="#cb28-8"></a></span>
<span id="cb28-9"><a href="#cb28-9"></a>Xre_train,Xre_test, yre_train,yre_test <span class="op">=</span> train_test_split(X_re_scaled, </span>
<span id="cb28-10"><a href="#cb28-10"></a>                                                          y_re, test_size<span class="op">=</span><span class="fl">0.2</span>, </span>
<span id="cb28-11"><a href="#cb28-11"></a>                                                          random_state<span class="op">=</span><span class="dv">41</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="random-forest-regressor" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-regressor">Random Forest Regressor</h3>
<p>Next, we set up a grid search to set up a random forest regressor.</p>
<div id="7af6558c" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1"></a>p_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">11</span>, <span class="dv">1</span>)</span>
<span id="cb29-2"><a href="#cb29-2"></a>rf_search <span class="op">=</span> GridSearchCV(RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">10</span>, random_state<span class="op">=</span><span class="dv">43</span>), </span>
<span id="cb29-3"><a href="#cb29-3"></a>                         {<span class="st">'max_depth'</span>: p_range}, </span>
<span id="cb29-4"><a href="#cb29-4"></a>                         scoring<span class="op">=</span><span class="st">'r2'</span>, cv<span class="op">=</span><span class="dv">5</span>, verbose<span class="op">=</span><span class="dv">1</span>, return_train_score<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb29-5"><a href="#cb29-5"></a>rf_search.fit(Xre_train, yre_train,)</span>
<span id="cb29-6"><a href="#cb29-6"></a>rf_search.best_estimator_<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 5 folds for each of 10 candidates, totalling 50 fits</code></pre>
</div>
</div>
<p>Here is the validation curve, that will allow us to decide on the optimal maximum depth, using 10 trees.</p>
<div id="cell-fig-taiwan-random-forest" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1"></a>train_means <span class="op">=</span> rf_search.cv_results_[<span class="st">'mean_train_score'</span>]</span>
<span id="cb31-2"><a href="#cb31-2"></a>train_sd <span class="op">=</span> rf_search.cv_results_[<span class="st">'std_train_score'</span>]</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a>test_means <span class="op">=</span> rf_search.cv_results_[<span class="st">'mean_test_score'</span>]</span>
<span id="cb31-5"><a href="#cb31-5"></a>test_sd <span class="op">=</span> rf_search.cv_results_[<span class="st">'std_test_score'</span>]</span>
<span id="cb31-6"><a href="#cb31-6"></a></span>
<span id="cb31-7"><a href="#cb31-7"></a>plt.plot(p_range, train_means, <span class="st">'o-'</span>, label<span class="op">=</span><span class="st">'Training'</span>, color<span class="op">=</span><span class="st">'blue'</span>)</span>
<span id="cb31-8"><a href="#cb31-8"></a>plt.fill_between(p_range, train_means<span class="op">-</span>train_sd, train_means<span class="op">+</span>train_sd, </span>
<span id="cb31-9"><a href="#cb31-9"></a>                 color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb31-10"><a href="#cb31-10"></a></span>
<span id="cb31-11"><a href="#cb31-11"></a>plt.plot(p_range, test_means, <span class="st">'o-'</span>, label<span class="op">=</span><span class="st">'CV (Test)'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb31-12"><a href="#cb31-12"></a>plt.fill_between(p_range, test_means<span class="op">-</span>test_sd, test_means<span class="op">+</span>test_sd, </span>
<span id="cb31-13"><a href="#cb31-13"></a>                 color<span class="op">=</span><span class="st">'red'</span>, alpha<span class="op">=</span><span class="fl">0.2</span>)</span>
<span id="cb31-14"><a href="#cb31-14"></a></span>
<span id="cb31-15"><a href="#cb31-15"></a>plt.legend(loc<span class="op">=</span><span class="st">'lower right'</span>)<span class="op">;</span>plt.ylabel(<span class="st">'R2'</span>)<span class="op">;</span></span>
<span id="cb31-16"><a href="#cb31-16"></a>plt.xlabel(<span class="st">'Complexity'</span>)<span class="op">;</span>plt.title(<span class="st">'Validation Curve'</span>)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-taiwan-random-forest" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-taiwan-random-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-taiwan-random-forest-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="589" height="449">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-taiwan-random-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.8: Validation curve, random forest for Taiwan data
</figcaption>
</figure>
</div>
</div>
</div>
<div id="exm-taiwan-data-14" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.8 (Taiwan data random forest regression)</strong></span> </p>
<p>Based on <a href="#fig-taiwan-random-forest" class="quarto-xref">Figure&nbsp;<span>8.8</span></a>, we shall fit a model with 10 trees and <code>max_depth</code> 2, and assess the <span class="math inline">\(R^2\)</span> on the test set.</p>
<div id="7d2ef1ab" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1"></a>rf1 <span class="op">=</span> RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">10</span>, max_depth <span class="op">=</span> <span class="dv">2</span>, random_state<span class="op">=</span><span class="dv">89</span>)</span>
<span id="cb32-2"><a href="#cb32-2"></a>rf1.fit(Xre_train, yre_train)</span>
<span id="cb32-3"><a href="#cb32-3"></a>yrf_pred <span class="op">=</span> rf1.predict(Xre_test)</span>
<span id="cb32-4"><a href="#cb32-4"></a>r2_score(yre_test, yrf_pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>0.5487486857968205</code></pre>
</div>
</div>
</div>
</section>
</section>
<section id="sec-08-interpretability" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="sec-08-interpretability"><span class="header-section-number">8.8</span> Interpretability of Models</h2>
<section id="lime" class="level3">
<h3 class="anchored" data-anchor-id="lime">LIME</h3>
<p>While the earlier methods indicated how we can understand the importance of features to the overall model, we have better tools to understand how features play a role in particular predictions. One such approach is known as LIME (Local Interpretable Model-Agnostic Explanations). A local model is one that explains why the model is making a particular prediction for a particular combination of feature values.</p>
<p>It works by training a <em>new model</em> that is inherently explainable, like a decision tree or a linear regression model, using instances that are weighted according to their proximity to the instance of interest. The new model’s prediction for this instance should be as close as possible to the prediction using the original model. To be precise, the steps are:</p>
<ol type="1">
<li>Select your instance of interest for which you want to have an explanation of its black box prediction.</li>
<li>Perturb your dataset and get the black box predictions for these new points.</li>
<li>Weight the new samples according to their proximity to the instance of interest.</li>
<li>Train a weighted, interpretable model on the dataset with the variations.</li>
</ol>
<p><a href="#fig-lime-fit" class="quarto-xref">Figure&nbsp;<span>8.9</span></a> visualises the process when making predictions (light-blue vs.&nbsp;gray) using two features (<span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>). The instance of interest is the yellow point.</p>
<div id="fig-lime-fit" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lime-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/lime-fitting-1.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lime-fit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.9: LIME
</figcaption>
</figure>
</div>
<div id="exm-taiwan-data-15" class="theorem example" style="background-color: #D5D1D164; padding: 20px">
<p><span class="theorem-title"><strong>Example 8.9 (Taiwan data LIME)</strong></span> </p>
<p>Now we return to our dataset on real estate transations and attempt to understand the prediction made for a particular instance:</p>
<div id="c2c48691" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1"></a>re_scaler.inverse_transform(Xre_test[<span class="dv">4</span>, :].reshape(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)).<span class="bu">round</span>()</span>
<span id="cb34-2"><a href="#cb34-2"></a><span class="co">#X_re.mean(axis=0).round(3)</span></span>
<span id="cb34-3"><a href="#cb34-3"></a><span class="co">#Xre_test[4, :].round(4)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>array([[2013.,   12., 1144.,    4.,    0.,    3.]])</code></pre>
</div>
</div>
<p>First we instantiate an explainer object, and then provide it with the instance we wish to explain.</p>
<div id="feff05d2" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1"></a>explainer <span class="op">=</span> lime_tabular.LimeTabularExplainer(</span>
<span id="cb36-2"><a href="#cb36-2"></a>    training_data<span class="op">=</span>np.array(Xre_train),</span>
<span id="cb36-3"><a href="#cb36-3"></a>    feature_names<span class="op">=</span>X_re.columns,</span>
<span id="cb36-4"><a href="#cb36-4"></a>    mode<span class="op">=</span><span class="st">'regression'</span>,</span>
<span id="cb36-5"><a href="#cb36-5"></a>)</span>
<span id="cb36-6"><a href="#cb36-6"></a>exp <span class="op">=</span> explainer.explain_instance(</span>
<span id="cb36-7"><a href="#cb36-7"></a>    data_row<span class="op">=</span>Xre_test[<span class="dv">4</span>, :], </span>
<span id="cb36-8"><a href="#cb36-8"></a>    predict_fn<span class="op">=</span>rf1.predict,</span>
<span id="cb36-9"><a href="#cb36-9"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-fig-taiwan-lime" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1"></a>exp.as_pyplot_figure()<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-taiwan-lime" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-taiwan-lime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="08-supervised_files/figure-html/fig-taiwan-lime-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="746" height="431">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-taiwan-lime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.10: LIME Explanation for Taiwan data instance
</figcaption>
</figure>
</div>
</div>
</div>
<p>Here is how we can interpret the plot in <a href="#fig-taiwan-lime" class="quarto-xref">Figure&nbsp;<span>8.10</span></a>. In terms of importance to the prediction <em>of this particular instance</em>, <code>dist_MRT</code> is the highest. The local model that has been fit has been constrained to make as close a prediction as possible to the original model. However, it may fall short. In this case, the original predicted value was 29.58. However, the value predicted by the local approximation was:</p>
<div id="8b5e2949" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1"></a><span class="bu">print</span>(<span class="ss">f"The value predicted by the local approximation was: </span><span class="sc">{</span>exp<span class="sc">.</span>local_pred[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The value predicted by the local approximation was: 33.747</code></pre>
</div>
</div>
<p>The numbers in the bar chart essentially decompose this prediction from the local model:</p>
<div id="e7335b5e" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1"></a>s <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="cf">for</span> x,y <span class="kw">in</span> exp.local_exp[<span class="dv">1</span>]:</span>
<span id="cb40-3"><a href="#cb40-3"></a>    s <span class="op">+=</span> y</span>
<span id="cb40-4"><a href="#cb40-4"></a></span>
<span id="cb40-5"><a href="#cb40-5"></a>s <span class="op">+</span> exp.intercept[<span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>np.float64(33.74709124579852)</code></pre>
</div>
</div>
<p>This means that, from the values, we can see that the <code>dist_MRT</code>, which was close to the average distance, had a negative impact on the price. So too did <code>house_age</code>. Meanwhile, longitude and latitude had a positive impact on the price.</p>
</div>
</section>
<section id="ice-plots" class="level3">
<h3 class="anchored" data-anchor-id="ice-plots">ICE plots</h3>
<p>ICE plots are conditional versions of PDP. Instead of <em>averaging</em> over all instances in the training set, a single line is generated for each instance corresponding to features other than the one under study. This allows us to inspect if the relationship between the response and the feature is consistent across the data.</p>
<div id="70eb27d2" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1"></a>_, ax <span class="op">=</span> plt.subplots(ncols<span class="op">=</span><span class="dv">2</span>, nrows<span class="op">=</span><span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">4</span>), constrained_layout<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb42-2"><a href="#cb42-2"></a>features_info <span class="op">=</span> {</span>
<span id="cb42-3"><a href="#cb42-3"></a>    <span class="st">"features"</span>: [<span class="dv">1</span>,<span class="dv">2</span>], <span class="co"># no names in the array; 1 and 2 correspond to house_age and dist_MRT</span></span>
<span id="cb42-4"><a href="#cb42-4"></a>    <span class="st">"kind"</span>: <span class="st">"both"</span>,</span>
<span id="cb42-5"><a href="#cb42-5"></a>}</span>
<span id="cb42-6"><a href="#cb42-6"></a>display <span class="op">=</span> PartialDependenceDisplay.from_estimator(</span>
<span id="cb42-7"><a href="#cb42-7"></a>    rf1,</span>
<span id="cb42-8"><a href="#cb42-8"></a>    Xre_train,</span>
<span id="cb42-9"><a href="#cb42-9"></a>    <span class="op">**</span>features_info,</span>
<span id="cb42-10"><a href="#cb42-10"></a>    ax<span class="op">=</span>ax</span>
<span id="cb42-11"><a href="#cb42-11"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="08-supervised_files/figure-html/cell-31-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="1163" height="395"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="summary" class="level2" data-number="8.9">
<h2 data-number="8.9" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.9</span> Summary</h2>
<p>We have only touched on a random forests and decision trees. However, there are numerous other (non-deep learning) machine learning models. Examples are <a href="https://scikit-learn.org/stable/modules/svm.html">Support Vector Machines</a>, <a href="https://scikit-learn.org/stable/modules/neighbors.html">Nearest Neighbours</a>, and <a href="https://scikit-learn.org/stable/modules/linear_model.html">Linear Models</a>. It would be good to skim through these models in the sklearn documentation to be aware of their existence. Instead of concentrating on learning a variety of shallow learning models, our topic has focused on the workflow when using these models, and how we should assess them. Nonetheless, it will be good if you can read up on your own on some of these models. The textbook ISL below is very good for learning about these models.</p>
<p>When working on your project, if you intend to perform supervised learning, please ensure that you also interpret the models, and do not leave them as a black box.</p>
</section>
<section id="references" class="level2" data-number="8.10">
<h2 data-number="8.10" class="anchored" data-anchor-id="references"><span class="header-section-number">8.10</span> References</h2>
<p>One of the best textbook references for this topic is <span class="citation" data-cites="hastie2009introduction">Hastie et al. (<a href="references.html#ref-hastie2009introduction" role="doc-biblioref">2009</a>)</span>. For more information on interpretable machine learning, refer to <span class="citation" data-cites="molnar2020interpretable">Molnar (<a href="references.html#ref-molnar2020interpretable" role="doc-biblioref">2020</a>)</span>. It is very comprehensive, with much more details on LIME and Shaply values.</p>
<section id="website-and-video-references" class="level3">
<h3 class="anchored" data-anchor-id="website-and-video-references">Website and video references</h3>
<ol type="1">
<li><a href="https://www.youtube.com/watch?v=_L39rN6gz7Y">Decision trees, clearly explained</a>: This is from a popular YouTube channel that explains stats and data science concepts.</li>
<li><a href="https://scikit-learn.org/stable/supervised_learning.html">sklearn documentation</a>: Documentation on available supervised learning models in sklearn.</li>
</ol>
</section>
<section id="documentation-references" class="level3">
<h3 class="anchored" data-anchor-id="documentation-references">Documentation references</h3>
<ol type="1">
<li><a href="https://christophm.github.io/interpretable-ml-book/">Interpretable Machine Learning</a>: A comprehensive textbook on interpreting machine learning models. See this book for more information about LIME and SHAPLY values.</li>
<li><a href="https://github.com/marcotcr/lime">LIME</a>: Full documentation on LIME
<ul>
<li><a href="https://www.youtube.com/watch?v=hUnRCxnydCc">Video introduction to LIME</a></li>
</ul></li>
</ol>
</section>
</section>
<section id="exercises" class="level2" data-number="8.11">
<h2 data-number="8.11" class="anchored" data-anchor-id="exercises"><span class="header-section-number">8.11</span> Exercises</h2>
<ol type="1">
<li>Refer back to the train-test-split that was used in <a href="#exm-heart-failure-2" class="quarto-xref">Example&nbsp;<span>8.2</span></a>. Instead of using all columns, use only <code>age</code>, <code>ejection_fraction</code>, <code>serum_creatinine</code>, <code>serum_sodium</code> and <code>time</code> to fit a decision tree classifier with <code>max_depth</code> = 2. Report the F1 score for this classifier on the test set.</li>
<li>Use the <code>clf</code> object from <a href="#exm-heart-failure-2" class="quarto-xref">Example&nbsp;<span>8.2</span></a> to return the predicted probability of <code>DEATH_EVENT=1</code> for row 0 of the <code>X_train</code> dataset.</li>
<li>Consider the confusion matrix in <a href="#fig-confusion-training" class="quarto-xref">Figure&nbsp;<span>8.3</span></a>. Extract the 4 observations corresponding to to the top-right entry in the table.</li>
<li>In medical settings, it is usually more important not to miss a true positive. This corresponds to the recall measure. Modify the code in <a href="#exm-heart-failure-6" class="quarto-xref">Example&nbsp;<span>8.6</span></a> to score the model using <code>recall</code>. How do the test set precision, recall and F1-score change?</li>
<li>The grid search in <a href="#exm-heart-failure-6" class="quarto-xref">Example&nbsp;<span>8.6</span></a> only tuned <code>max_depth</code>. Extend it to also search over n_estimators using values <code>[10, 20, 50, 100]</code>. You will need to modify the <code>param_grid</code> dictionary. Report the best combination of <code>(max_depth, n_estimators)</code> and the resulting test accuracy.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-hastie2009introduction" class="csl-entry" role="listitem">
Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2009. <em>An Introduction to Statistical Learning</em>.
</div>
<div id="ref-molnar2020interpretable" class="csl-entry" role="listitem">
Molnar, Christoph. 2020. <em>Interpretable Machine Learning</em>. Lulu. com.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-simulation.html" class="pagination-link" aria-label="Simulation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Simulation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-vision.html" class="pagination-link" aria-label="Computer Vision">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Computer Vision</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>